apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql  # Assuming your PostgreSQL pods are labeled with app=postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432  # PostgreSQL default port
