apiVersion: v1
kind: Service
metadata:
  name: my-elixir-app-service
  namespace: stord 
spec:
  selector:
    app: my-elixir-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer